export const SYSTEM_PERMISSIONS = [
  ['organizations', 'read'],
  ['organizations', 'update'],
  ['memberships', 'read'],
  ['memberships', 'invite'],
  ['memberships', 'update'],
  ['memberships', 'remove'],
  ['roles', 'read'],
  ['roles', 'create'],
  ['roles', 'update'],
  ['roles', 'delete'],
  ['permissions', 'read'],
  ['employees', 'read'],
  ['employees', 'create'],
  ['employees', 'update'],
  ['employees', 'delete'],
  ['recruitment', 'read'],
  ['recruitment', 'manage'],
  ['leave', 'read'],
  ['leave', 'request'],
  ['leave', 'approve'],
  ['attendance', 'read'],
  ['attendance', 'manage'],
  ['documents', 'read'],
  ['documents', 'manage'],
  ['tasks', 'read'],
  ['tasks', 'manage'],
  ['performance', 'read'],
  ['performance', 'manage'],
  ['training', 'read'],
  ['training', 'manage'],
  ['assets', 'read'],
  ['assets', 'manage'],
  ['reports', 'read'],
  ['reports', 'export'],
  ['audit', 'read'],
  ['billing', 'read'],
] as const;

export type SystemPermission = (typeof SYSTEM_PERMISSIONS)[number];
